### ISSUE TITLE
Login fails

### ISSUE THREAD

**Issue by NetworkNerd1337** [ebob9/get-all-interface-info#2]
After I attempt to login using a valid username (email address) and password I receive the following response "Profile retrieval failed.". I haven't found in the script where that error handling is. This happens whether I specify the username and password in the cloudgenix_settings.py file OR if I try to interactively login in through the console prompts when the script runs.

**Comment by ebob9** [comment]
This was an artifact of the new Palo Alto auth model, which now requires AUTH_TOKEN for legacy CloudGenix API calls.

I just released a new version, 2.0.1 - which supports the Palo Alto Prisma SASE APIs and using the new Service Account login construct - this can be entered interactively, similar to the old method
